[workspace]
members = [
	"api",
	"loglogd-tokio-uring",
	"loglog-tokio",
	"loglog",
	"loglogd",
	"e2e-tests",
]

[patch.crates-io]
watch = { git = "https://github.com/dpc/watch", branch="wait_timeout" }
